language: ruby
script:
  - bundle exec rake db:setup
  - bundle exec rspec
services:
  - postgresql
notifications:
  email:
    recipients:
    - matheusfvinhas@gmail.com
    on_success: always
    on_failure: always
before_install:
  - openssl aes-256-cbc -K $encrypted_700619d89018_key -iv $encrypted_700619d89018_iv -in .travis/deploy.key.enc -out .travis/deploy.key -d
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master

