language: ruby

script:
  - bundle exec rake db:setup
  - bundle exec rspec

services:
  - postgresql

notifications:
  email:
    recipients:
      - matheusfvinhas@gmail.com
    on_success: always
    on_failure: always


