default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ProjetoElabore_development

test:
  <<: *default
  database: ProjetoElabore_test

production:
  <<: *default
  database: ProjetoElabore_production
  username: ProjetoElabore
  password: <%= ENV['PROJETOELABORE_DATABASE_PASSWORD'] %>
